name: Integration Tests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: make deps

      - name: Run integration tests
        env:
          SLACK_MCP_OPENAI_API: ${{ secrets.SLACK_MCP_OPENAI_API }}
          SLACK_MCP_XOXP_TOKEN: ${{ secrets.SLACK_MCP_XOXP_TOKEN }}
          NGROK_AUTH_TOKEN:     ${{ secrets.NGROK_AUTH_TOKEN }}
        run: make test-integration
